A bunch of bugfixes (#277)
- Fix "Save as new" library item button
- Disable library item references due to bugs. Will enable in further
releases
- Lowercase demoapp resource names to match widespread Kafka topic
naming style
- Reuse same tenant names in demoapp
- Check that Dekaf license is not only valid, but also is active
- Fix Error generating ledger id:
org.apache.pulsar.metadata.api.MetadataStoreException:
org.rocksdb.RocksDBException: TimedOut(LockTimeout)
Pulsar Standalone still has issues with creating resources concurrently:
  - https://github.com/apache/pulsar/issues/15896
  - https://github.com/apache/pulsar/pull/16005
- Rely on existing Envoy in PATH instead of packing it to the dekaf.jar
- Remove Bookkeeper and RocksDB LOCK files before starting Dekaf Desktop
to fix flacky errors that happen on a standalone instance start. Anyway,
it's unlikely the local Pulsar instances data is very important
- Show connection color in the connections list
- Add "Copy logs" button
- Fix a bug where the desktop app failed in case a local pulsar instance
dir doesn't have a config file
- Fix demoapp reading env config
- Fill resource matcher input values on the matcher type change, where
possible
- Fix saving consumer session with Start From message id, date time, rel
date time
- Fix unnecessary topic selector requests
- Fix unnecessary library item count requests
- Fix the wrong GraalVM version for the desktop app
- Fix save "nth msg" Start From item to library
- Fix multiple minor bugs